// Code generated by controller generator. DO NOT EDIT.

package plugin_daemon

import (
	"github.com/langgenius/dify-plugin-daemon/internal/core/session_manager"
	"github.com/langgenius/dify-plugin-daemon/internal/utils/stream"
	"github.com/langgenius/dify-plugin-daemon/pkg/entities/dynamic_select_entities"
	"github.com/langgenius/dify-plugin-daemon/pkg/entities/requests"
)

func FetchDynamicParameterOptions(
	session *session_manager.Session,
	request *requests.RequestDynamicParameterSelect,
) (
	*stream.Stream[dynamic_select_entities.DynamicSelectResult], error,
) {
	return GenericInvokePlugin[requests.RequestDynamicParameterSelect, dynamic_select_entities.DynamicSelectResult](
		session,
		request,
		1,
	)
}
